/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.farmia.iot;
@org.apache.avro.specific.AvroGenerated
public enum AlertType implements org.apache.avro.generic.GenericEnumSymbol<AlertType> {
  HIGH_TEMPERATURE, LOW_HUMIDITY, HIGH_TEMPERATURE_AND_LOW_HUMIDITY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AlertType\",\"namespace\":\"com.farmia.iot\",\"symbols\":[\"HIGH_TEMPERATURE\",\"LOW_HUMIDITY\",\"HIGH_TEMPERATURE_AND_LOW_HUMIDITY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
